name: learn-github-actions
on:
  push:
    branches:
       - master
jobs:
  test-job:
    runs-on: ubuntu-18.04
    steps:
    - name: Connect to SSH
      uses: appleboy/ssh-action@master
      with:
            script: cd github-ci-cd && git pull origin master
            host: ${{ secrets.SAPHYR_PARIS_5_HOST }}
            username: ik04346
            key: ${{ secrets.SAPHYR_PARIS_5_PRIVATE }}   
